name: Berty Publish
on:
  push:
    branches:
      - main
jobs:
  valist-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: robinraju/release-downloader@v1.3
        with:
          repository: "berty/berty"
          latest: true
          tarBall: true
          zipBall: true
          fileName: "*"
      - uses: valist-io/valist-github-action@dev
        with:
          private-key: ${{ secrets.VALIST_SIGNER }}
          account: test0987-1
          project: test1
          release: 0.0.7
          path: '.'
          # this section is optional if you have a multi-platform release
          install-name: 'berty'
          install-darwin-amd64: './berty_darwin_amd64.tar.gz'
          install-darwin-arm64: './berty_darwin_arm64.tar.gz'
          install-linux-amd64: './berty_linux_amd64.tar.gz'
          install-windows-amd64: './berty_windows_amd64.zip'
