name: Valist Publish
on:
  push:
    branches:
      - main
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - run: echo "TIMESTAMP=$(date +%Y%m%d%H%M)" >> $GITHUB_ENV
      - uses: actions/checkout@v3
        with:
            path: '.'
      - uses: valist-io/valist-github-action@v2.5.2
        with:
          private-key: ${{ secrets.VALIST_SIGNER }}
          account: acme-co
          project: test1
          release: ${{ env.TIMESTAMP }}
          path: './build'
